apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  template: #todo debajo de template contiene los pods :)
    metadata:
      name: nginx
      labels:
        app: nginx
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
